<a href="https://colab.research.google.com/github/ancyjohn-726/Data_Acquisition_Casestudy/blob/main/DataAcquisition_Casestudy_AncyJohn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part A – Data Extraction

In [ ]:
import pandas as pd

In [ ]:
#TASK 1

filepath = '/content/population.csv'
population_df = pd.read_csv(filepath)
population_df

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [ ]:
population_df.shape

(25, 2)

In [ ]:
population_df.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [ ]:
population_df.dtypes

country       object
population     int64
dtype: object

In [ ]:
#TASK 2

filepath = '/content/gdp.xlsx'
gdp_df = pd.read_excel(filepath)
gdp_df

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [ ]:
gdp_df.columns

Index(['Country', 'GDP'], dtype='object')

In [ ]:
#TASK 3

internet_users_df=pd.read_json('/content/internet_users.json')
internet_users_df.head()

         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000

In [ ]:
internet_users_df.dtypes

country           object
internet_users     int64
dtype: object

In [ ]:
#TASK 4

filepath = '/content/literacy_rate.xml'
literacy_df = pd.read_xml(filepath)
literacy_df

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [ ]:
literacy_df.head()

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

In [ ]:
literacy_df.dtypes

name              object
literacy_rate    float64
dtype: object

Part B – Data Understanding

In [ ]:
#TASK 5

datasets = {
    'population': population_df,
    'gdp': gdp_df,
    'internet_users': internet_users_df,
    'literacy_rate': literacy_df
}

for name, df in datasets.items():
  print(f"\n{name}")
  print("rows and columns:", df.shape)
  print("Column names:",df.columns.tolist())
  print("\nData types:")
  print(df.dtypes)
  print("\nMissing values:")
  print(df.isnull().sum())
  print("Duplicate records:",df.duplicated().sum())

population
rows and columns: (25, 2)
Column names: ['country', 'population']

Data types:
country       object
population     int64
dtype: object

Missing values:
country       0
population    0
dtype: int64
Duplicate records: 0

gdp
rows and columns: (25, 2)
Column names: ['Country', 'GDP']

Data types:
Country    object
GDP         int64
dtype: object

Missing values:
Country    0
GDP        0
dtype: int64
Duplicate records: 0

internet_users
rows and columns: (25, 2)
Column names: ['country', 'internet_users']

Data types:
country           object
internet_users     int64
dtype: object

Missing values:
country           0
internet_users    0
dtype: int64
Duplicate records: 0

literacy_rate
rows and columns: (25, 2)
Column names: ['name', 'literacy_rate']

Data types:
name              object
literacy_rate    float64
dtype: object

Missing values:
name             0
literacy_rate    0
dtype: int64
Duplicate records: 0

Part C – Data Transformation

In [ ]:
#TASK 6

population_df.rename(columns={'Country':'country'}, inplace=True)
gdp_df.rename(columns={'Country':'country'}, inplace=True)
internet_users_df.rename(columns={'Country':'country'}, inplace=True)
literacy_df.rename(columns={'name':'country'}, inplace=True)
print(population_df.columns)
print(gdp_df.columns)
print(internet_users_df.columns)
print(literacy_df.columns)

Index(['country', 'population'], dtype='object')
Index(['country', 'GDP'], dtype='object')
Index(['country', 'internet_users'], dtype='object')
Index(['country', 'literacy_rate'], dtype='object')

In [ ]:
#TASK 7

population_df['population'] = pd.to_numeric(population_df['population'])
gdp_df['GDP'] = pd.to_numeric(gdp_df['GDP'])
internet_users_df['internet_users'] = pd.to_numeric(internet_users_df['internet_users'])
literacy_df['literacy_rate'] = pd.to_numeric(literacy_df['literacy_rate'])

print("Polulation")
print(population_df.dtypes)
print('\n')
print("GDP")
print(gdp_df.dtypes)
print('\n')
print("Internet")
print(internet_users_df.dtypes)
print('\n')
print("Literacy")
print(literacy_df.dtypes)

Polulation
country       object
population     int64
dtype: object


GDP
country    object
GDP         int64
dtype: object


Internet
country           object
internet_users     int64
dtype: object


Literacy
country           object
literacy_rate    float64
dtype: object

In [ ]:
# Task 8

import pandas as pd

merged_df = pd.merge(population_df, gdp_df, on="country", how="inner")
merged_df = pd.merge(merged_df, internet_users_df, on="country", how="inner")
merged_df = pd.merge(merged_df, literacy_df, on="country", how="inner")

merged_df

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

In [ ]:
# Task 9

merged_df["Internet Penetration (%)"] = (
    merged_df["internet_users"] / merged_df["population"] * 100
).round(2)

merged_df["GDP Per Capita"] = (
    merged_df["GDP"] * 1_000_000 / merged_df["population"]
).round(2)

print(merged_df.head())

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

   Internet Penetration (%)  GDP Per Capita
0                     94.26        92144.28
1                     76.50        13621.11
2                     61.59         3034.05
3                     93.77        33217.83
4                     94.91        56991.47

PART D

In [ ]:
# Task 10

import sqlite3

conn = sqlite3.connect("country_statistics.db")

merged_df.to_sql(
    "country_statistics",
    conn,
    if_exists="replace",
    index=False
)

conn.close()

In [ ]:
# Task 11

conn = sqlite3.connect("country_statistics.db")

check_df = pd.read_sql_query(
    "SELECT * FROM country_statistics LIMIT 5;",
    conn
)

print(check_df)

conn.close()

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

   Internet Penetration (%)  GDP Per Capita
0                     94.26        92144.28
1                     76.50        13621.11
2                     61.59         3034.05
3                     93.77        33217.83
4                     94.91        56991.47

PART E

In [ ]:
#1

print(merged_df.nlargest(5, "GDP")[["country", "GDP"]])

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [ ]:
# 2.

print(merged_df.nlargest(5, "population")[["country", "population"]])

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [ ]:
# 3.

print(merged_df["literacy_rate"].mean())

97.248

In [ ]:
# 4.

print(merged_df[merged_df["literacy_rate"] > 90][["country", "literacy_rate"]])

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [ ]:
# 5.

print(merged_df[merged_df["Internet Penetration (%)"] > 70][
    ["country", "Internet Penetration (%)"]])

           country  Internet Penetration (%)
0    United States                     94.26
1            China                     76.50
3            Japan                     93.77
4          Germany                     94.91
5   United Kingdom                     97.22
6           France                     94.98
7            Italy                     92.62
8           Canada                     94.72
9        Australia                     93.43
10          Brazil                     85.15
11          Russia                     85.65
12     South Korea                     96.56
13           Spain                     94.11
14          Mexico                     79.11
15       Indonesia                     77.51
16    Saudi Arabia                     97.66
17          Turkey                     81.81
18    South Africa                     72.50
19       Argentina                     90.72
20     Netherlands                     97.47
21     Switzerland                     98.21
22          Sweden                     97.55
23          Norway                     97.76
24       Singapore                     95.72

In [ ]:
# 6.

print(merged_df.nlargest(5, "GDP Per Capita")[["country", "GDP Per Capita"]])

          country  GDP Per Capita
21    Switzerland       108612.48
23         Norway       106986.57
0   United States        92144.28
24      Singapore        90592.99
9       Australia        73188.66

In [ ]:
# 7.

print(merged_df["population"].sum())

4720039725

In [ ]:
# 8.

print(merged_df["Internet Penetration (%)"].mean())

89.6596

In [ ]:
# 9.

print(merged_df.loc[
    merged_df["internet_users"].idxmax(),
    ["country", "internet_users"]])

country                China
internet_users    1080000000
Name: 1, dtype: object

In [ ]:
# 10.

print(merged_df["literacy_rate"].corr(merged_df["Internet Penetration (%)"]))

0.77279756813985

In [ ]:
conn = sqlite3.connect("country_statistics.db")

In [ ]:
# 11.

print(pd.read_sql_query("""
    SELECT country, GDP
    FROM country_statistics
    ORDER BY GDP DESC
    LIMIT 5;
""", conn))

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [ ]:
# 12.

print(pd.read_sql_query("""
    SELECT AVG(literacy_rate) AS average_literacy_rate
    FROM country_statistics;
""", conn))

   average_literacy_rate
0                 97.248

In [ ]:
# 13.

print(pd.read_sql_query("""
    SELECT country, literacy_rate
    FROM country_statistics
    WHERE literacy_rate > 90;
""", conn))

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            Japan           99.0
3          Germany           99.0
4   United Kingdom           99.0
5           France           99.0
6            Italy           99.0
7           Canada           99.0
8        Australia           99.0
9           Brazil           93.2
10          Russia           99.7
11     South Korea           98.8
12           Spain           98.6
13          Mexico           95.4
14       Indonesia           96.0
15    Saudi Arabia           97.3
16          Turkey           96.7
17    South Africa           95.0
18       Argentina           99.1
19     Netherlands           99.0
20     Switzerland           99.0
21          Sweden           99.0
22          Norway          100.0
23       Singapore           97.5

In [ ]:
# 14.

print(pd.read_sql_query("""
    SELECT country, "Internet Penetration (%)"
    FROM country_statistics
    ORDER BY "Internet Penetration (%)" DESC
    LIMIT 5;
""", conn))

        country  Internet Penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

In [ ]:
# 15.

print(pd.read_sql_query("""
    SELECT SUM(population) AS total_population
    FROM country_statistics;
""", conn))

   total_population
0        4720039725

In [ ]:
# 16.

print(pd.read_sql_query("""
    SELECT country, "GDP Per Capita"
    FROM country_statistics
    ORDER BY "GDP Per Capita" DESC
    LIMIT 1;
""", conn))

       country  GDP Per Capita
0  Switzerland       108612.48

In [ ]:
# 17.

merged_df.to_csv("country_statistics.csv", index=False)

In [ ]:
# 18.

print(pd.read_sql_query("""
    SELECT country, "GDP Per Capita"
    FROM country_statistics
    ORDER BY "GDP Per Capita" DESC
    LIMIT 10;
""", conn))

conn.close()

          country  GDP Per Capita
0     Switzerland       108612.48
1          Norway       106986.57
2   United States        92144.28
3       Singapore        90592.99
4       Australia        73188.66
5     Netherlands        65936.06
6          Sweden        62781.05
7          Canada        59202.37
8         Germany        56991.47
9  United Kingdom        56550.68